# Generated by Django 2.0.1 on 2018-02-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0012_auto_20180205_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='userimages/%m-%Y/'),
        ),
    ]
