# Generated by Django 2.0.1 on 2018-02-06 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0013_auto_20180205_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='reminder',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
