# Generated by Django 2.0.1 on 2018-02-07 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Todo', '0016_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='collab',
            field=models.ManyToManyField(related_name='notecollaborator', to=settings.AUTH_USER_MODEL),
        ),
    ]
