# Generated by Django 2.0.1 on 2018-02-07 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0017_notes_collab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='collab',
            field=models.ManyToManyField(blank=True, related_name='notecollaborator', to=settings.AUTH_USER_MODEL),
        ),
    ]
