# Generated by Django 2.0.1 on 2018-02-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0018_auto_20180207_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='ownername',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
