# Generated by Django 2.0.1 on 2018-02-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0019_notes_ownername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labels',
            name='note',
        ),
        migrations.AddField(
            model_name='notes',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='notelabel', to='Todo.Labels'),
        ),
    ]
