# Generated by Django 2.0.1 on 2018-02-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0021_notes_labelstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='photo',
            field=models.ImageField(blank=True, upload_to='userimages/%m-%Y/'),
        ),
    ]
