# Generated by Django 2.0.1 on 2018-02-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0023_notes_photourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='photourl',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
