# Generated by Django 2.0.1 on 2018-02-10 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0024_auto_20180210_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='photourl',
        ),
    ]
