# Generated by Django 2.0.1 on 2018-02-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0026_notes_photourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='photourl',
        ),
    ]
