# Generated by Django 2.0.1 on 2018-02-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0027_auto_20180210_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='photo',
            field=models.ImageField(blank=True, upload_to='userimages/%m-%Y/'),
        ),
        migrations.AddField(
            model_name='notes',
            name='photourl',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
